#!/bin/sh -login
#PBS -l mem=128GB
#PBS -l nodes=4:ppn=16:research
#PBS -l walltime=169:00:00
#PBS -N cldn23_mehdipour
#PBS -j oe


RUN_FILE="mpi_grid"
RUN_DIR="cloudy/runs/c17/mehdipour/grids/4thdex/cldn_23.00"

num_proc=$(cat ${PBS_NODEFILE} | wc -l)

module load openmpi/gnu/1.7.3

# replace ~/cloudy-agn/bin/cloudy_mpi with path to cloudy MPI executable file
cd ~/${RUN_DIR}
time mpirun -machinefile ${PBS_NODEFILE} -np ${num_proc} ~/cloudy/bin/cloudy_mpi -r ${RUN_FILE}
