#!/bin/sh -login
#PBS -l mem=128GB
#PBS -l nodes=4:ppn=16:research
#PBS -l walltime=169:00:00
#PBS -N ngc5548_cldn23
#PBS -j oe


RUN_FILE="mpi_grid"
RUN_DIR="cloudy/runs/4thdex_181515models_23cldn"

num_proc=$(cat ${PBS_NODEFILE} | wc -l)

module load openmpi/gnu/1.7.3

# replace ~/cloudy/cloudy_mpi with path to cloudy MPI executable file
cd ~/${RUN_DIR}
time mpirun -machinefile ${PBS_NODEFILE} -np ${num_proc} ~/cloudy/cloudy_mpi -r ${RUN_FILE}
